<a href="https://colab.research.google.com/github/AnaCristina1972/projett/blob/master/05_k_NN(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Métodos de AM tradicionais: **k Vizinhos Mais Próximos - kNN**
### Notas de aula

In [4]:
import pandas as pd
import numpy as np

### Dados

In [5]:
weather = {'ceu': ['ensolarado', 'ensolarado', 'nublado', 'chuvoso', 'chuvoso', 'chuvoso', 'nublado',
                     'ensolarado', 'ensolarado', 'chuvoso', 'ensolarado', 'nublado', 'nublado', 'chuvoso'],
          'temp': ['quente', 'quente', 'quente', 'media', 'fria', 'fria', 'fria',
                        'media', 'fria', 'media', 'media', 'media', 'quente', 'media'],
          'umidade': ['alta', 'alta', 'alta', 'alta', 'normal', 'normal', 'normal',
                     'alta', 'normal', 'normal', 'normal', 'alta', 'normal', 'alta'],
          'vento': ['F', 'V', 'F', 'F', 'F', 'V', 'V',
                  'F', 'F', 'F', 'V', 'V', 'F', 'V'],
          'jogar': ['F', 'F', 'V', 'V', 'V', 'F', 'V',
                 'F', 'V', 'V', 'V', 'V', 'V', 'F']}
wdf = pd.DataFrame(weather)[['ceu', 'temp', 'umidade', 'vento', 'jogar']]

In [6]:
wdf

ceu    temp umidade vento jogar
0   ensolarado  quente    alta     F     F
1   ensolarado  quente    alta     V     F
2      nublado  quente    alta     F     V
3      chuvoso   media    alta     F     V
4      chuvoso    fria  normal     F     V
5      chuvoso    fria  normal     V     F
6      nublado    fria  normal     V     V
7   ensolarado   media    alta     F     F
8   ensolarado    fria  normal     F     V
9      chuvoso   media  normal     F     V
10  ensolarado   media  normal     V     V
11     nublado   media    alta     V     V
12     nublado  quente  normal     F     V
13     chuvoso   media    alta     V     F

## Métodos baseados em instâncias -- $k$ Nearest Neighbors

Estes são métodos muito simples de classificação e regressão baseados na ideia de se encontrar um conjunto pré-definido de casos de treino similares à uma nova instância (os vizinhos) e prever a nova instância com base neles. O tamanho da vizinhança pode ser tanto dada em termos de um número fixo $k$ quanto em termos de um raio de distância. A distância pode ser medida por qualquer métrica, por exemplo, a euclidiana. Esses métodos não empregam técnicas de generalização já que eles lembram de todos os dados do treino.

Para um exemplo deste método, dada a coleção abaixo, qual a classe de uma instância `<ceu = ensolarado, temp = media, umidade = alta, vento = V>`, considerando $k$ = 1, 3, 5?

Para calcular o kNN vamos considerar a distância de Manhattan para o exemplo dado:

In [7]:
exemplo  = np.array(['ensolarado', 'media', 'alta', 'V'])
exemplo2 = np.array(['nublado', 'media', 'normal', 'F'])

In [8]:
exemplo == exemplo2   # compara 2 vetores

array([False,  True, False, False])

In [9]:
True + True, True + False, False + False

(2, 1, 0)

In [10]:
(exemplo == exemplo2).sum() # soma todos os valores do vetor resultante

1

In [11]:
def manhattan(row, vec):
    return 1 - (vec==row).sum()/row.shape[0]

In [12]:
wdf['dist'] = wdf.apply(lambda v: manhattan(v[:-1].values, exemplo), axis = 1)  # Erro se executado pela segunda vez

Para $k$=1, temos, jogar = F:

In [13]:
wdf.sort_values('dist').head(1)

ceu    temp umidade vento jogar  dist
1  ensolarado  quente    alta     V     F  0.25

Para $k$=3, temos jogar = F com 67% de certeza (2/3 dos vizinhos):

In [14]:
wdf.sort_values('dist').head(3)

ceu    temp umidade vento jogar  dist
1   ensolarado  quente    alta     V     F  0.25
7   ensolarado   media    alta     F     F  0.25
10  ensolarado   media  normal     V     V  0.25

Para $k$=5, temos jogar = F com 60% de certeza (3/5 dos vizinhos):

In [15]:
wdf.sort_values('dist').head(5)

ceu    temp umidade vento jogar  dist
1   ensolarado  quente    alta     V     F  0.25
7   ensolarado   media    alta     F     F  0.25
10  ensolarado   media  normal     V     V  0.25
11     nublado   media    alta     V     V  0.25
13     chuvoso   media    alta     V     F  0.25

#### Conclusões

O kNN consiste de uma família de métodos muito simples, muito usado como componente de diferentes outras técnicas (como estimativas de densidade). A maneira como uma decisão é inferida da vizinhança pode ou não considerar a similaridade dos vizinhos, através de ponderação. Implementações efetivas destes métodos devem recuperar as informações de treino com a ajuda de alguma estrutura de busca eficiente como uma KD-Tree ou uma Ball Tree.

In [16]:
from sklearn.datasets import load_iris

In [17]:
load_iris?

In [18]:
iris = load_iris()

In [19]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [20]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [21]:
iris.target_names[iris.target]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
Xtrain, Xteste, ytrain, yteste = train_test_split(iris.data, iris.target, test_size= 0.3, stratify= iris.target)

In [24]:
Xtrain.shape, Xteste.shape, ytrain.shape, yteste.shape

((105, 4), (45, 4), (105,), (45,))

In [25]:
pd.Series(ytrain).value_counts()

2    35
0    35
1    35
dtype: int64

In [26]:
100*pd.Series(ytrain).value_counts() / len(ytrain) # amostra aleatórios desbalanceada

2    33.333333
0    33.333333
1    33.333333
dtype: float64

In [27]:
100*pd.Series(yteste).value_counts() / len(yteste) # amostras aleatórias desbalanceada

0    33.333333
1    33.333333
2    33.333333
dtype: float64

In [28]:
100*pd.Series(iris.target).value_counts() / 150 #perfeitamente balanceada

0    33.333333
1    33.333333
2    33.333333
dtype: float64

In [29]:
from sklearn.neighbors import KNeighborsClassifier

In [30]:
neigh = KNeighborsClassifier(n_neighbors=5)

In [31]:
neigh

KNeighborsClassifier()

In [32]:
neigh.fit(Xtrain,ytrain)

KNeighborsClassifier()

In [33]:
ypred = neigh.predict(Xteste)

In [34]:
ypred

array([0, 1, 0, 1, 0, 2, 1, 0, 2, 0, 2, 0, 0, 2, 2, 0, 1, 0, 2, 0, 2, 2,
       1, 0, 0, 1, 1, 0, 0, 2, 1, 2, 2, 1, 1, 0, 2, 2, 2, 1, 1, 2, 1, 2,
       1])

In [35]:
from sklearn.metrics import accuracy_score

In [36]:
accuracy_score(yteste, ypred)

0.9777777777777777